FROM ubuntu:latest

# to avoid interaction for installing TZdata
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && apt update \
    && useradd -ms /bin/bash layewang \
    && echo "layewang:toorroot!" | chpasswd \
    && adduser layewang sudo \
    && apt install -y python3 \
    && apt install -y python3-pip \
    && apt install -y ffmpeg \
    && apt install -y aria2 \
    && pip install youtube_dl \
    && pip install bypy

ENV PUID= \
    PGID=

CMD ["/bin/bash"]