FROM codercom/code-server:latest

# to avoid interaction for installing TZdata
ENV PATH "/home/coder/conda/bin:${PATH}"

USER 1000
RUN sudo apt-get update \
    && sudo apt-get install -y wget \

    # install chrome (optional)
    && sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && sudo apt-get -y install -f ./google-chrome-stable_current_amd64.deb \
    && sudo rm ./google-chrome-stable_current_amd64.deb \

    # Clean apt-cache
    && sudo apt autoremove -y \
    && sudo apt clean -y \
    && sudo rm -rf /var/lib/apt/lists/* \

    # install oh-my-zsh (zsh already installed in base image)
    && zsh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)" \
    && sudo chsh -s $(which zsh) \

    # install Conda
    && wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh --quiet \
    && bash ~/miniconda.sh -b -p /home/coder/conda/ \
    && rm ~/miniconda.sh \
    && conda install -y python=3.9.7 \
    && conda init zsh \
    && conda init bash \

    # setup my conda env
    && conda update -y --all \
    && conda create -y -n backtest_rqalpha python==3.9.7 \
    && conda create -y -n my_portfolio_analysis python==3.9.7 \
    && conda create -y -n ofanalysis python==3.9.7 \
    && conda create -y -n general python==3.9.7 \
    && conda clean --all -f -y \

    # set up codeserver
    && code-server --install-extension alefragnani.project-manager \
    && code-server --install-extension formulahendry.code-runner \
    && code-server --install-extension zhuangtongfa.material-theme \
    && code-server --install-extension vscode-icons-team.vscode-icons \
    && code-server --install-extension ms-python.python \
    && code-server --install-extension mongodb.mongodb-vscode \
    && code-server --install-extension KevinRose.vsc-python-indent \
    && code-server --install-extension njpwerner.autodocstring \
    && code-server --install-extension humao.rest-client \
    && code-server --install-extension hediet.vscode-drawio \
    && code-server --install-extension redhat.vscode-yaml \
    && code-server --install-extension GrapeCity.gc-excelviewer

COPY --chown=1000 ./settings.json /home/coder/.local/share/code-server/User/
