name: Docker Image Builder

on:
  workflow_dispatch:
    inputs:
      image_folder:
        description: "image category [DEV, VPS]"
        required: true
        default: "DEV"
      image_name:
        description: "image name"
        required: true
      image_tag:
        description: "image tag"
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # build 并且 push docker 镜像
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./DOCKER/${{ github.event.inputs.image_folder }}/${{ github.event.inputs.image_name }}/
          file: ./DOCKER/${{ github.event.inputs.image_folder }}/${{ github.event.inputs.image_name }}/DOCKERFILE
          push: true
          tags: |
            laye0619/${{ github.event.inputs.image_name }}:latest
            laye0619/${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_tag }}
