name: Docker Image Builder

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      image_folder:
        description: "image category [DEV, VPS]"
        required: true
        default: "DEV"
      image_name:
        description: "image name"
        required: true
      image_tag:
        description: "image tag"
        required: true

env:
  DOCKER_IMAGE_FOLDER: github.event.inputs.image_folder
  DOCKER_IMAGE_NAME: github.event.inputs.image_name
  TAG: github.event.inputs.image_tag

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # build 并且 push docker 镜像
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./DOCKER/${{ env.DOCKER_IMAGE_FOLDER }}/${{ env.DOCKER_IMAGE_NAME }}/
          file: ./DOCKER/${{ env.DOCKER_IMAGE_FOLDER }}/${{ env.DOCKER_IMAGE_NAME }}/DOCKERFILE
          push: true
          tags: |
            laye0619/${{ env.DOCKER_IMAGE_NAME }}:latest
            laye0619/${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}
