name: build docker image dev_env_codeserver.

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
     # build 并且 push docker 镜像
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./DOCKERFILE/DEV/dev_env_codeserver/
          file: ./DOCKERFILE/DEV/dev_env_codeserver/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dev_env_codeserver:latest
