name: Generate 'my_clash_config.yaml'

on:
  schedule:
  - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install sshpass

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests

    - name: Generate clash config and upload to home server
      run: |
        echo "${{ secrets.MY_CLASH_INFO }}">>./clash_rule/my_config_need_to_add_into.yaml
        cat ./clash_rule/my_config_need_to_add_into.yaml
        python -u ./clash_rule/get_clash_config.py
        sshpass -p ${{ secrets.HOME_SERVER_PASS }} scp -P 18100 -o StrictHostKeyChecking=no ./clash_rule/my_clash_config.yaml layewang@home.laye.wang:/home/layewang/Docker/openwrt/etc/openclash/config/