# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TAG: 0.6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2

    # docker login
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # 设置 docker 环境
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    # build 并且 push docker 镜像
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./DOCKERFILE/DEV/dev_env_codeserver/
        file: ./DOCKERFILE/DEV/dev_env_codeserver/Dockerfile
        push: true
        tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/dev_env_codeserver:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/dev_env_codeserver::${{ env.TAG }}
    # 打印 docker 镜像 SHA256 Hash 值
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
