#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'release tag'
        required: true
        default: 'my_official'
      repo:
        description: 'repo of openwrt'
        required: true
        default: 'https://www.github.com/openwrt/openwrt'
      branch:
        description: 'repo branch'
        required: true
        default: 'master'
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  TAG:  ${{ github.event.inputs.tag }}
  REPO_URL: ${{ github.event.inputs.repo }}
  REPO_BRANCH: ${{ github.event.inputs.branch }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::${{ env.TAG }}_$(date +"%m%d")"
        echo "::set-output name=status::success"
    
    - name: comfirm release tag
      run: |
        echo ${{ steps.tag.outputs.release_tag }}
        

